### ISSUE TITLE
It doesn't install on virtualbox

### ISSUE THREAD

**Issue by oldcastlehq** [venomlinux/venomiso#2]
Hello.
I'm new here.

I cannot install Venom on virtualbox. Did anyone try?

The installer exit when creating the user.

**Comment by emmett1** [comment]
Which iso did you use?

**Comment by oldcastlehq** [comment]
I tried with Mate and Xfce. Exactly same error.

**Comment by emmett1** [comment]
Which version of iso? I need to know.
Whats the error?
Is it UEFI or not?
What disk type? Gpt or mbr?
What partition scheme you set up?

**Comment by dlzi** [comment]
- the latest version
- It doesn't show an error, it just exit the installer (any tip how can I see the error?)
- UEFI
- HDD a HP laptop
- /swap 1GB and a / (ext4)  7GB

**Comment by oldcastlehq** [comment]
- the latest version
- It doesn't show an error, it just exit the installer (any tip how can I see the error?)
- UEFI
- HDD a HP laptop
- /swap 1GB and a / (ext4) 7GB

**Comment by emmett1** [comment]
You did not answer gpt or mbr. If its UEFI, gpt is required.

**Comment by emmett1** [comment]
For EFI systems, GPT partition is required and a FAT32 partition with at least 100MB set as 'EFI System' must be created.

**Comment by oldcastlehq** [comment]
I just tried install on a mbr..it didn't work.

![Screenshot from 2020-05-13 23-52-02](https://user-images.githubusercontent.com/20318144/81841589-e5100a00-9574-11ea-82d6-ef9edd4ef8c6.png)

**Comment by emmett1** [comment]
I think you are using gpt disk type instead of dos. Why dont you try again and choose dos for disk type.

**Comment by oldcastlehq** [comment]
It worked. I needed to use dos disk type. 

Thank you!

**Comment by emmett1** [comment]
Nice. I’m glad it worked for you now😃.
So many people faced same problem as yours. I will fix installer to avoid this happen again on next release.
